# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - develop
    - releases/*
    - feature/*
    
pool:
  vmImage: ubuntu-latest
    
    
stages:
- stage: A
  jobs:
  - job: A1
    steps:

    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
      
  - job: A2
    dependsOn: A1

- stage: B
  jobs:
  - job: B1
  - job: B2

- stage: deployment
  jobs:
  - deployment: deployProd     
    pool:
      vmImage: ubuntu-latest
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hi!
          
          
