
variables:
  COMPOSER_CACHE_DIR: $(Pipeline.Workspace)/.composer
  SYMFONY_VENDOR_DIR: $(Build.SourcesDirectory)/vendor
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  hasDeploy: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/develop') )]


trigger:
  branches:
    include:
    - master
    - develop
    - releases/*
    - feature/*
    
pool:
  vmImage: ubuntu-latest
    
    
stages:
- stage: Prepare
  jobs:
  
    
  - job: "ComposerInstall"
    steps:
      - script: ls -l $(Build.SourcesDirectory)
        displayName: show workspace dir content 
    
      - task: Cache@2
        inputs:
          key: 'composer | "$(Agent.OS)" | composer.lock'
          restoreKeys: |
            composer | "$(Agent.OS)"
            composer
          path: $(COMPOSER_CACHE_DIR)
        displayName: Cache composer  
          
      - task: Cache@2
        inputs:
          key: 'vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"'
          restoreKeys: |
            vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"
            vendor | "$(Agent.OS)"
            vendor
#          restoreKeys: 'vendor | vendor/**'
          path: $(SYMFONY_VENDOR_DIR)
        displayName: Cache vendors
          
      - script: composer install
        displayName: install composer dependencies
        
- stage: Test
  jobs:
  
    
  - job: PhpUnit
    steps:
    - task: Cache@2
      inputs:
        key: 'composer | "$(Agent.OS)" | composer.lock'
        restoreKeys: |
          composer | "$(Agent.OS)"
          composer
        path: $(COMPOSER_CACHE_DIR)
      displayName: Cache composer
      
    - task: Cache@2
      inputs:
        key: 'vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"'
        restoreKeys: |
          vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"
          vendor | "$(Agent.OS)"
          vendor
        path: $(SYMFONY_VENDOR_DIR)
      displayName: Cache vendors
      
    - script: composer require --dev phpunit/phpunit symfony/test-pack
      displayName: install phpUnit
    
    - script: php ./vendor/bin/phpunit
      displayName: execute tests
      
  - job: Phpmd
    container: jakzal/phpqa:latest
    steps:
    - task: Cache@2
      inputs:
        key: 'composer | "$(Agent.OS)" | composer.lock'
        restoreKeys: |
          composer | "$(Agent.OS)"
          composer
        path: $(COMPOSER_CACHE_DIR)
      displayName: Cache composer
      
    - task: Cache@2
      inputs:
        key: 'vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"'
        restoreKeys: |
          vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"
          vendor | "$(Agent.OS)"
          vendor
        path: $(SYMFONY_VENDOR_DIR)
      displayName: Cache vendors
     
      
    - script: phpmd src xml phpmd.xml 
      displayName: phpmd
      
  - job: Phploc
    container: jakzal/phpqa:latest
    steps:
    - task: Cache@2
      inputs:
        key: 'composer | "$(Agent.OS)" | composer.lock'
        restoreKeys: |
          composer | "$(Agent.OS)"
          composer
        path: $(COMPOSER_CACHE_DIR)
      displayName: Cache composer
      
    - task: Cache@2
      inputs:
        key: 'vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"'
        restoreKeys: |
          vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"
          vendor | "$(Agent.OS)"
          vendor
        path: $(SYMFONY_VENDOR_DIR)
      displayName: Cache vendors
     
      
    - script: phploc src tests --log-xml=phploc.xml --count-tests 
      displayName: phploc   
      
      
  - job: Phpcs
    container: jakzal/phpqa:latest
    steps:
    - task: Cache@2
      inputs:
        key: 'composer | "$(Agent.OS)" | composer.lock'
        restoreKeys: |
          composer | "$(Agent.OS)"
          composer
        path: $(COMPOSER_CACHE_DIR)
      displayName: Cache composer
      
    - task: Cache@2
      inputs:
        key: 'vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"'
        restoreKeys: |
          vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"
          vendor | "$(Agent.OS)"
          vendor
        path: $(SYMFONY_VENDOR_DIR)
      displayName: Cache vendors
     
      
    - script: phpcs src
      displayName: phpcs 
      
  - job: Php_cs_fixer
    container: jakzal/phpqa:latest
    steps:
    - task: Cache@2
      inputs:
        key: 'composer | "$(Agent.OS)" | composer.lock'
        restoreKeys: |
          composer | "$(Agent.OS)"
          composer
        path: $(COMPOSER_CACHE_DIR)
      displayName: Cache composer
      
    - task: Cache@2
      inputs:
        key: 'vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"'
        restoreKeys: |
          vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"
          vendor | "$(Agent.OS)"
          vendor
        path: $(SYMFONY_VENDOR_DIR)
      displayName: Cache vendors
     
      
    - script: php-cs-fixer
      displayName: php-cs-fixer fix --dry-run --allow-risky=yes --no-interaction --ansi
      
- stage: A
  dependsOn: Prepare
  jobs:
  - job: A1
    steps:

    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
      
  - job: A2
    dependsOn: A1

- stage: B
  dependsOn: Prepare
  jobs:
  - job: B1
  - job: B2

- stage: deployment
  dependsOn: [A, B]
  condition: eq(variables.hasDeploy, true)
  jobs:
  - deployment: deployProd     
    condition: eq(variables.isMain, true)
    pool:
      vmImage: ubuntu-latest
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hi!
          
  - deployment: deployTest     
    condition: eq(variables.isMain, false)
    pool:
      vmImage: ubuntu-latest
    environment: test
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hi!
  - job: notify
    steps:
    - script: echo notify
      displayName: send notification
          
- stage: Document
  dependsOn: [Test]  
  jobs:
  - job: Phpdocumentor
    container: jakzal/phpqa:latest
    steps:
    - task: Cache@2
      inputs:
        key: 'composer | "$(Agent.OS)" | composer.lock'
        restoreKeys: |
          composer | "$(Agent.OS)"
          composer
        path: $(COMPOSER_CACHE_DIR)
      displayName: Cache composer
      
    - task: Cache@2
      inputs:
        key: 'vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"'
        restoreKeys: |
          vendor | "$(Agent.OS)" | "$(Build.SourceBranch)"
          vendor | "$(Agent.OS)"
          vendor
        path: $(SYMFONY_VENDOR_DIR)
      displayName: Cache vendors
     
      
    - script: phpDocumentor
      displayName: phpDocumentor  
  
