
variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]


trigger:
  branches:
    include:
    - master
    - develop
    - releases/*
    - feature/*
    
pool:
  vmImage: ubuntu-latest
    
    
stages:
- stage: Prepare
  jobs:
  - job: Composer 
    steps:
      - script: composer install
        displayName: install composer dependencies
  
- stage: A
  jobs:
  - job: A1
    steps:

    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
      
  - job: A2
    dependsOn: A1

- stage: B
  jobs:
  - job: B1
  - job: B2

- stage: deployment
  jobs:
  - deployment: deployProd     
    condition: eq(variables.isMain, true)
    pool:
      vmImage: ubuntu-latest
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hi!
  - job: notify
    steps:
    - script: echo notify
      displayName: send notification
          
          
