version: "2.1"
services:
    db:
        image: mysql
        container_name: db_docker
        restart: always
        volumes:
            - db-data-sso:/var/lib/mysqlsso
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker
        restart: always
        depends_on:
            - db
        ports:
            - 8081:80
        environment:
            PMA_HOST: db

    sso:
        extends:
            file: docker-compose.base.yml
            service: php
        container_name: www_docker_symfony_sso
        ports:
          - "8082:80"
        volumes:
            - ./:/var/www
        restart: always

networks:
    default:
        external:
            name: dev
volumes:
    db-data-sso: {}